"""Primitive root detection and search algorithm (runnable MVP).

This script demonstrates:
1) Existence check for primitive roots modulo n.
2) Primitive root search for valid n.
3) Correctness verification by generated residue classes.

Run:
    python3 demo.py
"""

from __future__ import annotations

from math import gcd
from typing import Dict, List, Set


def factorize(n: int) -> Dict[int, int]:
    """Return prime factorization of n as {prime: exponent} via trial division."""
    if n <= 0:
        raise ValueError("factorize expects a positive integer")

    x = n
    factors: Dict[int, int] = {}

    while x % 2 == 0:
        factors[2] = factors.get(2, 0) + 1
        x //= 2

    f = 3
    while f * f <= x:
        while x % f == 0:
            factors[f] = factors.get(f, 0) + 1
            x //= f
        f += 2

    if x > 1:
        factors[x] = factors.get(x, 0) + 1

    return factors


def phi(n: int) -> int:
    """Euler's totient function using prime factorization."""
    if n <= 0:
        raise ValueError("phi expects a positive integer")

    result = n
    for p in factorize(n):
        result = result // p * (p - 1)
    return result


def is_odd_prime_power(n: int) -> bool:
    """Check whether n is p^k for an odd prime p and k >= 1."""
    if n <= 1:
        return False

    fac = factorize(n)
    if len(fac) != 1:
        return False

    (p, _exp), = fac.items()
    return p % 2 == 1


def has_primitive_root(n: int) -> bool:
    """Return True iff primitive roots modulo n exist.

    Criterion:
        n has primitive roots iff n in {2, 4, p^k, 2*p^k}
        where p is an odd prime and k >= 1.
    """
    if n == 2 or n == 4:
        return True
    if n <= 1:
        return False

    if n % 2 == 0:
        m = n // 2
        # n = 2 * p^k requires m odd.
        if m % 2 == 0:
            return False
        return is_odd_prime_power(m)

    # odd case: n must be odd prime power
    return is_odd_prime_power(n)


def prime_factors_of_phi(n: int) -> List[int]:
    """Prime factors of phi(n), sorted ascending."""
    return sorted(factorize(phi(n)).keys())


def is_primitive_root(g: int, n: int) -> bool:
    """Check whether g is a primitive root modulo n."""
    if not has_primitive_root(n):
        return False
    if gcd(g, n) != 1:
        return False

    phi_n = phi(n)
    for q in prime_factors_of_phi(n):
        if pow(g, phi_n // q, n) == 1:
            return False
    return True


def find_primitive_root(n: int) -> int:
    """Find one primitive root modulo n, or raise ValueError if none exists."""
    if not has_primitive_root(n):
        raise ValueError(f"mod {n} has no primitive root")

    if n == 2:
        return 1

    phi_n = phi(n)
    factors_phi = prime_factors_of_phi(n)

    for g in range(2, n):
        if gcd(g, n) != 1:
            continue
        ok = True
        for q in factors_phi:
            if pow(g, phi_n // q, n) == 1:
                ok = False
                break
        if ok:
            return g

    raise RuntimeError(f"primitive root should exist but not found for n={n}")


def reduced_residue_system(n: int) -> Set[int]:
    """Set of residues in [1, n-1] coprime with n."""
    return {x for x in range(1, n) if gcd(x, n) == 1}


def generated_by_root(g: int, n: int) -> Set[int]:
    """Set generated by powers of g modulo n over exponent range [0, phi(n)-1]."""
    phi_n = phi(n)
    return {pow(g, k, n) for k in range(phi_n)}


def demo_table() -> None:
    """Print a compact table for existence and one primitive root if available."""
    ns = [2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 15, 17, 18, 19, 21, 25, 27, 31, 32]

    print("=== Primitive Root Existence & Search ===")
    print(f"{'n':>4} | {'has_root':>8} | {'phi(n)':>6} | {'one_root':>8} | {'verified':>8}")
    print("-" * 52)

    for n in ns:
        exists = has_primitive_root(n)
        phi_n = phi(n)
        if exists:
            g = find_primitive_root(n)
            verified = generated_by_root(g, n) == reduced_residue_system(n)
            print(f"{n:>4} | {str(exists):>8} | {phi_n:>6} | {g:>8} | {str(verified):>8}")
        else:
            print(f"{n:>4} | {str(exists):>8} | {phi_n:>6} | {'-':>8} | {'-':>8}")


def demo_detailed_example(n: int) -> None:
    """Show one detailed example for a modulus with primitive roots."""
    if not has_primitive_root(n):
        print(f"mod {n} has no primitive root, skip detailed demo.")
        return

    g = find_primitive_root(n)
    phi_n = phi(n)
    sequence = [pow(g, k, n) for k in range(phi_n)]

    print("\n=== Detailed Example ===")
    print(f"n = {n}, phi(n) = {phi_n}, primitive root g = {g}")
    print(f"g^k mod n for k = 0..{phi_n - 1}:")
    print(sequence)
    print("distinct count:", len(set(sequence)))
    print("equals reduced residue system:", set(sequence) == reduced_residue_system(n))


def main() -> None:
    demo_table()
    demo_detailed_example(17)


if __name__ == "__main__":
    main()
