"""Todd-Coxeter coset enumeration MVP.

This script implements a transparent, small-scale coset enumerator for
finitely presented groups:
    G = < X | R >
and a subgroup H generated by subgroup words.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

Word = List[int]


@dataclass
class CosetEnumerationResult:
    index: int
    table: List[List[int]]
    generator_perms: Dict[str, Tuple[int, ...]]


class SymbolCodec:
    """Encode generators/inverses into integer symbols.

    For k generators:
      symbol 2*i   -> generator i
      symbol 2*i+1 -> inverse generator i
    """

    def __init__(self, generator_names: Sequence[str]) -> None:
        names = list(generator_names)
        if not names:
            raise ValueError("At least one generator is required")
        if len(set(names)) != len(names):
            raise ValueError("Generator names must be unique")
        if any((not n.isalpha()) or (len(n) != 1) or (not n.islower()) for n in names):
            raise ValueError("Use one lowercase alphabet character per generator")

        self.names = names
        self.name_to_idx = {name: i for i, name in enumerate(names)}
        self.n_symbols = 2 * len(names)

    def inv(self, symbol: int) -> int:
        return symbol ^ 1

    def parse_word(self, token_string: str) -> Word:
        """Parse words like 'abAB' where uppercase means inverse."""
        out: Word = []
        for ch in token_string:
            if ch.isspace():
                continue
            lower = ch.lower()
            if lower not in self.name_to_idx:
                raise ValueError(f"Unknown symbol '{ch}' in word '{token_string}'")
            idx = self.name_to_idx[lower]
            out.append(2 * idx + (1 if ch.isupper() else 0))
        return out

    def invert_word(self, word: Sequence[int]) -> Word:
        return [self.inv(s) for s in reversed(word)]

    def gen_symbol(self, generator_name: str) -> int:
        idx = self.name_to_idx[generator_name]
        return 2 * idx


class ToddCoxeter:
    def __init__(
        self,
        codec: SymbolCodec,
        relators: Sequence[Word],
        subgroup_words: Sequence[Word],
        max_cosets: int = 256,
    ) -> None:
        self.codec = codec
        self.relators: List[Word] = []
        for r in relators:
            if not r:
                continue
            self.relators.append(list(r))
            self.relators.append(codec.invert_word(r))
        self.subgroup_words = [list(w) for w in subgroup_words if w]
        self.max_cosets = max_cosets

        # 1-based rows; row 0 is unused.
        self.table: List[List[int]] = [[0] * self.codec.n_symbols]
        self.parent: List[int] = [0]
        self.rank: List[int] = [0]
        self.mod_count = 0

        self._new_coset()  # coset 1 = H

    def _rep(self, c: int) -> int:
        parent = self.parent
        while parent[c] != c:
            parent[c] = parent[parent[c]]
            c = parent[c]
        return c

    def _new_coset(self) -> int:
        if len(self.table) - 1 >= self.max_cosets:
            raise RuntimeError(
                f"Coset limit exceeded (max_cosets={self.max_cosets}); "
                "the index may be too large or infinite for this bound."
            )
        self.table.append([0] * self.codec.n_symbols)
        idx = len(self.table) - 1
        self.parent.append(idx)
        self.rank.append(0)
        self.mod_count += 1
        return idx

    def _merge(self, a: int, b: int) -> bool:
        ra, rb = self._rep(a), self._rep(b)
        if ra == rb:
            return False

        if self.rank[ra] < self.rank[rb]:
            ra, rb = rb, ra
        self.parent[rb] = ra
        if self.rank[ra] == self.rank[rb]:
            self.rank[ra] += 1
        self.mod_count += 1

        row_ra = self.table[ra]
        row_rb = self.table[rb]
        for s in range(self.codec.n_symbols):
            x = row_ra[s]
            y = row_rb[s]
            if x == 0 and y != 0:
                y_rep = self._rep(y)
                row_ra[s] = y_rep
                inv_s = self.codec.inv(s)
                back = self.table[y_rep][inv_s]
                if back == 0:
                    self.table[y_rep][inv_s] = ra
                    self.mod_count += 1
                else:
                    self._merge(back, ra)
            elif x != 0 and y != 0:
                self._merge(x, y)
        return True

    def _define(self, c: int, s: int, d: int) -> bool:
        rc, rd = self._rep(c), self._rep(d)

        cur = self.table[rc][s]
        if cur != 0:
            return self._merge(cur, rd)

        self.table[rc][s] = rd
        self.mod_count += 1
        inv_s = self.codec.inv(s)
        back = self.table[rd][inv_s]
        if back == 0:
            self.table[rd][inv_s] = rc
            self.mod_count += 1
            return True
        return self._merge(back, rc)

    def _scan_and_fill(self, start: int, word: Sequence[int], end: int) -> bool:
        """Enforce: start * word = end."""
        if not word:
            return self._merge(start, end)

        x = self._rep(start)
        y = self._rep(end)

        i = 0
        f = x
        n = len(word)
        while i < n:
            nxt = self.table[f][word[i]]
            if nxt == 0:
                break
            f = self._rep(nxt)
            i += 1

        j = n - 1
        b = y
        while j >= i:
            nxt = self.table[b][self.codec.inv(word[j])]
            if nxt == 0:
                break
            b = self._rep(nxt)
            j -= 1

        if i > j:
            return self._merge(f, b)

        if i == j:
            return self._define(f, word[i], b)

        changed = False
        cur = f
        for k in range(i, j):
            nxt = self._new_coset()
            changed = self._define(cur, word[k], nxt) or changed
            cur = self._rep(nxt)
        changed = self._define(cur, word[j], b) or changed
        return changed

    def _live_representatives(self) -> List[int]:
        reps: List[int] = []
        for c in range(1, len(self.table)):
            if self._rep(c) == c:
                reps.append(c)
        return reps

    def close_under_constraints(self) -> None:
        while True:
            before = self.mod_count

            reps = self._live_representatives()
            for c in reps:
                c_rep = self._rep(c)
                for rel in self.relators:
                    self._scan_and_fill(c_rep, rel, c_rep)

            root = self._rep(1)
            for subw in self.subgroup_words:
                self._scan_and_fill(root, subw, root)

            if self.mod_count == before:
                return

    def _find_hole(self) -> Optional[Tuple[int, int]]:
        for c in self._live_representatives():
            row = self.table[c]
            for s in range(self.codec.n_symbols):
                if row[s] == 0:
                    return c, s
        return None

    def enumerate(self) -> None:
        self.close_under_constraints()
        while True:
            hole = self._find_hole()
            if hole is None:
                return
            c, s = hole
            d = self._new_coset()
            self._define(c, s, d)
            self.close_under_constraints()

    def standardized_table(self) -> List[List[int]]:
        reps = self._live_representatives()
        rep_to_new = {old: new for new, old in enumerate(reps, start=1)}

        out: List[List[int]] = [[0] * self.codec.n_symbols for _ in range(len(reps) + 1)]
        for old in reps:
            new_row = rep_to_new[old]
            for s in range(self.codec.n_symbols):
                tgt = self.table[old][s]
                if tgt == 0:
                    raise RuntimeError("Coset table is incomplete after enumeration")
                out[new_row][s] = rep_to_new[self._rep(tgt)]
        return out

    def generator_action_permutations(self, std_table: List[List[int]]) -> Dict[str, Tuple[int, ...]]:
        n = len(std_table) - 1
        actions: Dict[str, Tuple[int, ...]] = {}
        for g in self.codec.names:
            s = self.codec.gen_symbol(g)
            perm = tuple(std_table[row][s] for row in range(1, n + 1))
            actions[g] = perm
        return actions


def run_case(
    name: str,
    generator_names: Sequence[str],
    relator_strings: Sequence[str],
    subgroup_word_strings: Sequence[str],
    expected_index: int,
    max_cosets: int = 256,
) -> None:
    codec = SymbolCodec(generator_names)
    relators = [codec.parse_word(w) for w in relator_strings]
    subgroup_words = [codec.parse_word(w) for w in subgroup_word_strings]

    tc = ToddCoxeter(
        codec=codec,
        relators=relators,
        subgroup_words=subgroup_words,
        max_cosets=max_cosets,
    )
    tc.enumerate()

    std = tc.standardized_table()
    index = len(std) - 1
    actions = tc.generator_action_permutations(std)

    print(f"\n[{name}]")
    print(f"  index (cosets)     : {index}")
    print(f"  table shape        : {index} x {codec.n_symbols}")
    for g in generator_names:
        print(f"  action of {g:<1}      : {actions[g]}")

    assert index == expected_index, (
        f"{name}: expected index {expected_index}, got {index}"
    )


def main() -> None:
    # S3 = <a,b | a^2, b^3, (ab)^2>, H=<a>, index = 3
    run_case(
        name="S3 / <a>",
        generator_names=["a", "b"],
        relator_strings=["aa", "bbb", "abab"],
        subgroup_word_strings=["a"],
        expected_index=3,
    )

    # D4 = <a,b | a^4, b^2, babA>, H=<a>, index = 2
    run_case(
        name="D4 / <a>",
        generator_names=["a", "b"],
        relator_strings=["aaaa", "bb", "babA"],
        subgroup_word_strings=["a"],
        expected_index=2,
    )

    # S3 with trivial subgroup H={e}, index = |S3| = 6
    run_case(
        name="S3 / {e}",
        generator_names=["a", "b"],
        relator_strings=["aa", "bbb", "abab"],
        subgroup_word_strings=[],
        expected_index=6,
    )

    print("\nAll checks passed.")


if __name__ == "__main__":
    main()
