"""Minimal runnable MVP for Poisson Bracket (PHYS-0113).

The script demonstrates three core checks:
1) Canonical fundamental Poisson brackets.
2) Jacobi identity residual on nonlinear observables.
3) Hamiltonian time evolution generated by Poisson brackets.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import numpy as np
import pandas as pd


Observable = Callable[[np.ndarray], float]


@dataclass
class PoissonConfig:
    fd_eps: float = 1e-6
    canonical_n_dof: int = 2
    jacobi_sample_points: int = 8
    jacobi_tol: float = 2e-5

    mass: float = 1.7
    stiffness: float = 2.3
    q0: float = 0.9
    p0: float = -0.35
    dt: float = 1e-3
    steps: int = 4000

    q_error_tol: float = 6e-4
    p_error_tol: float = 8e-4
    energy_drift_tol: float = 8e-4
    hamilton_rhs_tol: float = 2e-4


def central_partial_derivative(f: Observable, z: np.ndarray, idx: int, eps: float) -> float:
    """Compute partial derivative df/dz_idx via central finite difference."""
    z_plus = z.astype(np.float64, copy=True)
    z_minus = z.astype(np.float64, copy=True)
    z_plus[idx] += eps
    z_minus[idx] -= eps
    return float((f(z_plus) - f(z_minus)) / (2.0 * eps))


def poisson_bracket(f: Observable, g: Observable, z: np.ndarray, n_dof: int, eps: float) -> float:
    """Compute {f,g} = sum_i(df/dq_i * dg/dp_i - df/dp_i * dg/dq_i)."""
    if z.ndim != 1:
        raise ValueError("State z must be a 1-D vector.")
    if z.shape[0] != 2 * n_dof:
        raise ValueError("State dimension must equal 2*n_dof.")

    total = 0.0
    for i in range(n_dof):
        dq_i = i
        dp_i = n_dof + i

        df_dq = central_partial_derivative(f, z, dq_i, eps)
        df_dp = central_partial_derivative(f, z, dp_i, eps)
        dg_dq = central_partial_derivative(g, z, dq_i, eps)
        dg_dp = central_partial_derivative(g, z, dp_i, eps)

        total += df_dq * dg_dp - df_dp * dg_dq

    return float(total)


def q_observable(i: int) -> Observable:
    """Return observable q_i."""

    def obs(z: np.ndarray) -> float:
        return float(z[i])

    return obs


def p_observable(i: int, n_dof: int) -> Observable:
    """Return observable p_i."""

    def obs(z: np.ndarray) -> float:
        return float(z[n_dof + i])

    return obs


def bracket_observable(f: Observable, g: Observable, n_dof: int, eps: float) -> Observable:
    """Return observable z -> {f,g}(z)."""

    def obs(z: np.ndarray) -> float:
        return poisson_bracket(f, g, z, n_dof=n_dof, eps=eps)

    return obs


def canonical_bracket_report(config: PoissonConfig) -> tuple[dict[str, float], pd.DataFrame]:
    """Validate {q_i,q_j}=0, {p_i,p_j}=0, {q_i,p_j}=delta_ij."""
    n = config.canonical_n_dof
    z_ref = np.array([0.30, -0.80, 1.10, 0.45], dtype=np.float64)

    qq = np.zeros((n, n), dtype=np.float64)
    pp = np.zeros((n, n), dtype=np.float64)
    qp = np.zeros((n, n), dtype=np.float64)

    for i in range(n):
        qi = q_observable(i)
        pi = p_observable(i, n)
        for j in range(n):
            qj = q_observable(j)
            pj = p_observable(j, n)

            qq[i, j] = poisson_bracket(qi, qj, z_ref, n_dof=n, eps=config.fd_eps)
            pp[i, j] = poisson_bracket(pi, pj, z_ref, n_dof=n, eps=config.fd_eps)
            qp[i, j] = poisson_bracket(qi, pj, z_ref, n_dof=n, eps=config.fd_eps)

    eye = np.eye(n, dtype=np.float64)
    report = {
        "max_abs_qq": float(np.max(np.abs(qq))),
        "max_abs_pp": float(np.max(np.abs(pp))),
        "max_abs_qp_minus_delta": float(np.max(np.abs(qp - eye))),
    }

    table = pd.DataFrame(
        {
            "entry": ["max|{q_i,q_j}|", "max|{p_i,p_j}|", "max|{q_i,p_j}-delta_ij|"],
            "value": [report["max_abs_qq"], report["max_abs_pp"], report["max_abs_qp_minus_delta"]],
        }
    )
    return report, table


def jacobi_identity_report(config: PoissonConfig) -> tuple[dict[str, float], pd.DataFrame]:
    """Evaluate Jacobi residual on nonlinear observables."""
    n = config.canonical_n_dof

    def f(z: np.ndarray) -> float:
        q1, q2, p1, p2 = z
        return float(q1 * q1 * p2 + 0.5 * q2 - 0.2 * p1)

    def g(z: np.ndarray) -> float:
        q1, q2, p1, p2 = z
        return float(q2 * q2 + p1 * p2 + 0.3 * q1)

    def h(z: np.ndarray) -> float:
        q1, q2, p1, p2 = z
        return float(q1 * p1 - q2 * p2 + 0.1 * p2 * p2 * p2)

    gh = bracket_observable(g, h, n_dof=n, eps=config.fd_eps)
    hf = bracket_observable(h, f, n_dof=n, eps=config.fd_eps)
    fg = bracket_observable(f, g, n_dof=n, eps=config.fd_eps)

    points: list[np.ndarray] = []
    for k in range(config.jacobi_sample_points):
        t = (k + 1) / (config.jacobi_sample_points + 1)
        points.append(
            np.array(
                [
                    -0.9 + 1.8 * t,
                    0.7 - 1.4 * t,
                    -0.6 + 1.2 * t,
                    0.3 + 0.9 * t,
                ],
                dtype=np.float64,
            )
        )

    residuals = []
    for z in points:
        term1 = poisson_bracket(f, gh, z, n_dof=n, eps=config.fd_eps)
        term2 = poisson_bracket(g, hf, z, n_dof=n, eps=config.fd_eps)
        term3 = poisson_bracket(h, fg, z, n_dof=n, eps=config.fd_eps)
        residuals.append(term1 + term2 + term3)

    residuals_arr = np.asarray(residuals, dtype=np.float64)
    report = {
        "jacobi_max_abs": float(np.max(np.abs(residuals_arr))),
        "jacobi_mean_abs": float(np.mean(np.abs(residuals_arr))),
    }

    table = pd.DataFrame(
        {
            "sample_id": np.arange(1, residuals_arr.size + 1),
            "jacobi_residual": residuals_arr,
            "abs_residual": np.abs(residuals_arr),
        }
    )
    return report, table


def hamiltonian_1d_harmonic(mass: float, stiffness: float) -> Observable:
    """Return H(q,p)=p^2/(2m)+kq^2/2 for one degree of freedom."""

    def h(z: np.ndarray) -> float:
        q = float(z[0])
        p = float(z[1])
        return 0.5 * (p * p) / mass + 0.5 * stiffness * (q * q)

    return h


def hamiltonian_vector_field(z: np.ndarray, h: Observable, eps: float) -> np.ndarray:
    """Return z_dot generated by z_dot_i={z_i,H} for (q,p)."""
    q = q_observable(0)
    p = p_observable(0, n_dof=1)
    dq_dt = poisson_bracket(q, h, z, n_dof=1, eps=eps)
    dp_dt = poisson_bracket(p, h, z, n_dof=1, eps=eps)
    return np.array([dq_dt, dp_dt], dtype=np.float64)


def rk4_step(z: np.ndarray, dt: float, field: Callable[[np.ndarray], np.ndarray]) -> np.ndarray:
    """One RK4 step for z' = field(z)."""
    k1 = field(z)
    k2 = field(z + 0.5 * dt * k1)
    k3 = field(z + 0.5 * dt * k2)
    k4 = field(z + dt * k3)
    return z + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)


def harmonic_oscillator_report(config: PoissonConfig) -> tuple[dict[str, float], pd.DataFrame]:
    """Simulate 1D harmonic oscillator and compare with analytic trajectory."""
    h = hamiltonian_1d_harmonic(config.mass, config.stiffness)
    z0 = np.array([config.q0, config.p0], dtype=np.float64)

    times = config.dt * np.arange(config.steps + 1, dtype=np.float64)
    traj = np.zeros((config.steps + 1, 2), dtype=np.float64)
    traj[0] = z0

    field = lambda zz: hamiltonian_vector_field(zz, h=h, eps=config.fd_eps)
    for k in range(config.steps):
        traj[k + 1] = rk4_step(traj[k], config.dt, field)

    q_num = traj[:, 0]
    p_num = traj[:, 1]

    omega = np.sqrt(config.stiffness / config.mass)
    q_exact = config.q0 * np.cos(omega * times) + (config.p0 / (config.mass * omega)) * np.sin(omega * times)
    p_exact = config.p0 * np.cos(omega * times) - (config.mass * omega * config.q0) * np.sin(omega * times)

    q_err = np.abs(q_num - q_exact)
    p_err = np.abs(p_num - p_exact)

    energy = np.array([h(z) for z in traj], dtype=np.float64)
    energy_rel_drift = np.abs(energy - energy[0]) / max(1e-15, abs(energy[0]))

    rhs = np.array([field(z) for z in traj], dtype=np.float64)
    dq_dt_num = np.gradient(q_num, config.dt)
    dp_dt_num = np.gradient(p_num, config.dt)
    dq_rhs_rmse = float(np.sqrt(np.mean((dq_dt_num - rhs[:, 0]) ** 2)))
    dp_rhs_rmse = float(np.sqrt(np.mean((dp_dt_num - rhs[:, 1]) ** 2)))

    report = {
        "q_max_abs_error": float(np.max(q_err)),
        "p_max_abs_error": float(np.max(p_err)),
        "energy_max_rel_drift": float(np.max(energy_rel_drift)),
        "dq_rhs_rmse": dq_rhs_rmse,
        "dp_rhs_rmse": dp_rhs_rmse,
    }

    table = pd.DataFrame(
        {
            "t": times,
            "q_num": q_num,
            "q_exact": q_exact,
            "p_num": p_num,
            "p_exact": p_exact,
            "energy": energy,
            "q_abs_err": q_err,
            "p_abs_err": p_err,
        }
    )
    return report, table


def main() -> None:
    config = PoissonConfig()

    canonical_report, canonical_table = canonical_bracket_report(config)
    jacobi_report, jacobi_table = jacobi_identity_report(config)
    ho_report, ho_table = harmonic_oscillator_report(config)

    checks = {
        "canonical max|{q,q}| < 1e-10": canonical_report["max_abs_qq"] < 1e-10,
        "canonical max|{p,p}| < 1e-10": canonical_report["max_abs_pp"] < 1e-10,
        "canonical max|{q,p}-delta| < 5e-10": canonical_report["max_abs_qp_minus_delta"] < 5e-10,
        "jacobi max residual < jacobi_tol": jacobi_report["jacobi_max_abs"] < config.jacobi_tol,
        "harmonic q max error < q_error_tol": ho_report["q_max_abs_error"] < config.q_error_tol,
        "harmonic p max error < p_error_tol": ho_report["p_max_abs_error"] < config.p_error_tol,
        "energy max relative drift < energy_drift_tol": ho_report["energy_max_rel_drift"] < config.energy_drift_tol,
        "hamilton eq RMSE < hamilton_rhs_tol": max(ho_report["dq_rhs_rmse"], ho_report["dp_rhs_rmse"])
        < config.hamilton_rhs_tol,
    }

    print("=== Poisson Bracket MVP (PHYS-0113) ===")
    print(
        "Config: fd_eps={eps:.1e}, dt={dt:.1e}, steps={steps}, mass={m:.3f}, stiffness={k:.3f}".format(
            eps=config.fd_eps,
            dt=config.dt,
            steps=config.steps,
            m=config.mass,
            k=config.stiffness,
        )
    )

    print("\n[Canonical bracket checks]")
    print(canonical_table.to_string(index=False))

    print("\n[Jacobi identity residual summary]")
    print(
        "jacobi_max_abs={mx:.3e}, jacobi_mean_abs={mn:.3e}".format(
            mx=jacobi_report["jacobi_max_abs"],
            mn=jacobi_report["jacobi_mean_abs"],
        )
    )
    print("sample rows:")
    print(jacobi_table.head(6).to_string(index=False))

    print("\n[Harmonic oscillator via Poisson dynamics]")
    print(
        "q_max_abs_error={q:.3e}, p_max_abs_error={p:.3e}, energy_max_rel_drift={e:.3e}, "
        "dq_rhs_rmse={dq:.3e}, dp_rhs_rmse={dp:.3e}".format(
            q=ho_report["q_max_abs_error"],
            p=ho_report["p_max_abs_error"],
            e=ho_report["energy_max_rel_drift"],
            dq=ho_report["dq_rhs_rmse"],
            dp=ho_report["dp_rhs_rmse"],
        )
    )
    print("sample trajectory rows:")
    print(ho_table.head(8).to_string(index=False))

    print("\nThreshold checks:")
    for name, ok in checks.items():
        print(f"- {name}: {'OK' if ok else 'FAIL'}")

    if all(checks.values()):
        print("\nValidation: PASS")
    else:
        raise SystemExit("Validation: FAIL")


if __name__ == "__main__":
    main()
