"""Canonical transformation MVP on a 1D harmonic oscillator.

We verify a time-independent canonical transformation generated by:
    F2(q, P) = q P - (alpha/2) q^2
which implies
    Q = dF2/dP = q
    p = dF2/dq = P - alpha q  ->  P = p + alpha q

This demo checks three aspects:
1) Symplectic condition: J^T Omega J = Omega.
2) Poisson bracket: {Q, P}_{q,p} = 1.
3) Dynamics equivalence: integrating in (q,p) vs (Q,P) gives the same physical orbit after mapping.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd
from scipy.integrate import solve_ivp


@dataclass(frozen=True)
class CanonicalParams:
    """Physical and numerical configuration."""

    mass: float = 1.0
    stiffness: float = 4.0
    alpha: float = 0.8
    q0: float = 0.7
    p0: float = -0.2
    t_end: float = 20.0
    n_eval: int = 2001


def validate_params(params: CanonicalParams) -> None:
    """Check parameter validity."""

    if params.mass <= 0.0:
        raise ValueError("mass must be positive")
    if params.stiffness <= 0.0:
        raise ValueError("stiffness must be positive")
    if not np.isfinite(params.alpha):
        raise ValueError("alpha must be finite")
    if params.t_end <= 0.0:
        raise ValueError("t_end must be positive")
    if params.n_eval < 3:
        raise ValueError("n_eval must be >= 3")
    if not np.isfinite(params.q0) or not np.isfinite(params.p0):
        raise ValueError("q0 and p0 must be finite")


def forward_transform(q: np.ndarray | float, p: np.ndarray | float, alpha: float) -> tuple[np.ndarray | float, np.ndarray | float]:
    """(q,p) -> (Q,P): Q=q, P=p+alpha*q."""

    q_arr = np.asarray(q)
    p_arr = np.asarray(p)
    q_new = q_arr
    p_new = p_arr + alpha * q_arr
    return q_new, p_new


def inverse_transform(Q: np.ndarray | float, P: np.ndarray | float, alpha: float) -> tuple[np.ndarray | float, np.ndarray | float]:
    """(Q,P) -> (q,p): q=Q, p=P-alpha*Q."""

    Q_arr = np.asarray(Q)
    P_arr = np.asarray(P)
    q_old = Q_arr
    p_old = P_arr - alpha * Q_arr
    return q_old, p_old


def jacobian_matrix(alpha: float) -> np.ndarray:
    """Jacobian J = d(Q,P)/d(q,p)."""

    return np.array([[1.0, 0.0], [alpha, 1.0]], dtype=float)


def symplectic_residual(alpha: float) -> float:
    """Infinity-norm residual of J^T Omega J - Omega."""

    J = jacobian_matrix(alpha)
    omega = np.array([[0.0, 1.0], [-1.0, 0.0]], dtype=float)
    residual = J.T @ omega @ J - omega
    return float(np.linalg.norm(residual, ord=np.inf))


def poisson_bracket_qp(alpha: float) -> float:
    """Compute {Q,P}_{q,p} analytically for this linear mapping."""

    dQ_dq = 1.0
    dQ_dp = 0.0
    dP_dq = alpha
    dP_dp = 1.0
    return dQ_dq * dP_dp - dQ_dp * dP_dq


def hamiltonian_original(q: np.ndarray | float, p: np.ndarray | float, params: CanonicalParams) -> np.ndarray | float:
    """Original Hamiltonian H(q,p) = p^2/(2m) + (k/2) q^2."""

    q_arr = np.asarray(q)
    p_arr = np.asarray(p)
    return (p_arr * p_arr) / (2.0 * params.mass) + 0.5 * params.stiffness * (q_arr * q_arr)


def hamiltonian_transformed(Q: np.ndarray | float, P: np.ndarray | float, params: CanonicalParams) -> np.ndarray | float:
    """Transformed Hamiltonian K(Q,P) = H(q(Q,P), p(Q,P))."""

    Q_arr = np.asarray(Q)
    P_arr = np.asarray(P)
    p_old = P_arr - params.alpha * Q_arr
    return (p_old * p_old) / (2.0 * params.mass) + 0.5 * params.stiffness * (Q_arr * Q_arr)


def rhs_original(_t: float, y: np.ndarray, params: CanonicalParams) -> np.ndarray:
    """Hamilton equations in original variables."""

    q, p = y
    dq_dt = p / params.mass
    dp_dt = -params.stiffness * q
    return np.array([dq_dt, dp_dt], dtype=float)


def rhs_transformed(_t: float, y: np.ndarray, params: CanonicalParams) -> np.ndarray:
    """Hamilton equations in transformed variables K(Q,P)."""

    Q, P = y
    dQ_dt = (P - params.alpha * Q) / params.mass
    dP_dt = (params.alpha / params.mass) * (P - params.alpha * Q) - params.stiffness * Q
    return np.array([dQ_dt, dP_dt], dtype=float)


def integrate_original(params: CanonicalParams, t_eval: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Integrate original system and return q(t), p(t)."""

    sol = solve_ivp(
        fun=lambda t, y: rhs_original(t, y, params),
        t_span=(0.0, float(t_eval[-1])),
        y0=np.array([params.q0, params.p0], dtype=float),
        method="DOP853",
        t_eval=t_eval,
        rtol=1e-11,
        atol=1e-13,
    )
    if not sol.success:
        raise RuntimeError(f"original integration failed: {sol.message}")
    return sol.y[0], sol.y[1]


def integrate_transformed(params: CanonicalParams, t_eval: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Integrate transformed system and return Q(t), P(t)."""

    Q0, P0 = forward_transform(params.q0, params.p0, params.alpha)
    y0 = np.array([float(Q0), float(P0)], dtype=float)
    sol = solve_ivp(
        fun=lambda t, y: rhs_transformed(t, y, params),
        t_span=(0.0, float(t_eval[-1])),
        y0=y0,
        method="DOP853",
        t_eval=t_eval,
        rtol=1e-11,
        atol=1e-13,
    )
    if not sol.success:
        raise RuntimeError(f"transformed integration failed: {sol.message}")
    return sol.y[0], sol.y[1]


def max_relative_drift(values: np.ndarray) -> float:
    """Max relative drift from first sample."""

    baseline = max(1.0, abs(float(values[0])))
    return float(np.max(np.abs(values - values[0])) / baseline)


def rhs_chain_rule_residual(Q: float, P: float, params: CanonicalParams) -> float:
    """Residual between transformed RHS and chain-rule mapped original RHS."""

    q, p = inverse_transform(Q, P, params.alpha)
    rhs_old = rhs_original(0.0, np.array([float(q), float(p)], dtype=float), params)
    rhs_chain = np.array([rhs_old[0], rhs_old[1] + params.alpha * rhs_old[0]], dtype=float)
    rhs_new = rhs_transformed(0.0, np.array([Q, P], dtype=float), params)
    return float(np.linalg.norm(rhs_new - rhs_chain, ord=np.inf))


def build_report(params: CanonicalParams) -> pd.DataFrame:
    """Run full experiment and return diagnostics as a table."""

    t_eval = np.linspace(0.0, params.t_end, params.n_eval)

    q, p = integrate_original(params, t_eval)
    Q, P = integrate_transformed(params, t_eval)

    q_from_new, p_from_new = inverse_transform(Q, P, params.alpha)
    q_from_new = np.asarray(q_from_new, dtype=float)
    p_from_new = np.asarray(p_from_new, dtype=float)

    H = np.asarray(hamiltonian_original(q, p, params), dtype=float)
    K = np.asarray(hamiltonian_transformed(Q, P, params), dtype=float)

    J = jacobian_matrix(params.alpha)
    det_J = float(np.linalg.det(J))

    sample_idx = np.linspace(0, params.n_eval - 1, 11, dtype=int)
    chain_rule_res = [rhs_chain_rule_residual(float(Q[i]), float(P[i]), params) for i in sample_idx]

    rows = [
        {"metric": "symplectic_residual_inf", "value": f"{symplectic_residual(params.alpha):.3e}"},
        {"metric": "poisson_bracket_QP", "value": f"{poisson_bracket_qp(params.alpha):.6f}"},
        {"metric": "jacobian_det", "value": f"{det_J:.6f}"},
        {"metric": "max_abs_q_mismatch", "value": f"{np.max(np.abs(q - q_from_new)):.3e}"},
        {"metric": "max_abs_p_mismatch", "value": f"{np.max(np.abs(p - p_from_new)):.3e}"},
        {"metric": "original_energy_rel_drift", "value": f"{max_relative_drift(H):.3e}"},
        {"metric": "transformed_energy_rel_drift", "value": f"{max_relative_drift(K):.3e}"},
        {"metric": "max_abs_H_minus_K", "value": f"{np.max(np.abs(H - K)):.3e}"},
        {"metric": "max_chain_rule_rhs_res", "value": f"{max(chain_rule_res):.3e}"},
        {"metric": "final_q", "value": f"{q[-1]:.6f}"},
        {"metric": "final_p", "value": f"{p[-1]:.6f}"},
    ]

    return pd.DataFrame(rows)


def main() -> None:
    """Entry point."""

    params = CanonicalParams()
    validate_params(params)

    report = build_report(params)

    print("=== Canonical Transformation MVP (1D Harmonic Oscillator) ===")
    print(
        "params:",
        {
            "mass": params.mass,
            "stiffness": params.stiffness,
            "alpha": params.alpha,
            "q0": params.q0,
            "p0": params.p0,
            "t_end": params.t_end,
            "n_eval": params.n_eval,
        },
    )
    print(report.to_string(index=False))

    # Minimal quality gates for the MVP.
    as_float = {row["metric"]: float(row["value"]) for _, row in report.iterrows()}
    if as_float["symplectic_residual_inf"] > 1e-12:
        raise AssertionError("symplectic residual too large")
    if abs(as_float["poisson_bracket_QP"] - 1.0) > 1e-12:
        raise AssertionError("Poisson bracket check failed")
    if as_float["max_abs_q_mismatch"] > 5e-8 or as_float["max_abs_p_mismatch"] > 5e-8:
        raise AssertionError("trajectory mismatch between frames is too large")
    if as_float["max_chain_rule_rhs_res"] > 1e-11:
        raise AssertionError("RHS chain-rule consistency failed")


if __name__ == "__main__":
    main()
