"""Educational birthday-attack MVP.

This script demonstrates collision search on truncated SHA-256 outputs.
It is intentionally small and reproducible: no interactive input required.
"""

from __future__ import annotations

import hashlib
import math
import time
from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class CollisionResult:
    """One successful collision-search outcome."""

    bits: int
    attempts: int
    digest_value: int
    message_a: bytes
    message_b: bytes
    elapsed_seconds: float


def truncated_sha256_bits(message: bytes, bits: int) -> int:
    """Return the first `bits` bits of SHA-256(message) as an integer."""
    if bits <= 0 or bits > 256:
        raise ValueError("bits must be in [1, 256]")

    digest = hashlib.sha256(message).digest()
    byte_len = (bits + 7) // 8
    value = int.from_bytes(digest[:byte_len], "big")
    extra_bits = byte_len * 8 - bits
    if extra_bits:
        value >>= extra_bits
    return value


def digest_hex(value: int, bits: int) -> str:
    """Format a truncated digest integer as fixed-width hex."""
    hex_width = (bits + 3) // 4
    return f"0x{value:0{hex_width}x}"


def build_candidate_message(rng: np.random.Generator, counter: int) -> bytes:
    """Generate deterministic-but-diverse candidate messages."""
    nonce = counter.to_bytes(8, "big")
    noise = rng.integers(0, 256, size=16, dtype=np.uint8).tobytes()
    return nonce + noise


def expected_attempts(bits: int) -> float:
    """Approximate expected attempts until first collision."""
    return math.sqrt(math.pi / 2.0) * (2.0 ** (bits / 2.0))


def find_first_collision(bits: int, seed: int, max_attempts: int) -> CollisionResult:
    """Search until first collision on truncated SHA-256(bits)."""
    rng = np.random.default_rng(seed)
    seen: dict[int, bytes] = {}

    t0 = time.perf_counter()
    for attempt in range(1, max_attempts + 1):
        message = build_candidate_message(rng, attempt)
        digest_value = truncated_sha256_bits(message, bits)

        previous = seen.get(digest_value)
        if previous is None:
            seen[digest_value] = message
            continue

        if previous == message:
            # Extremely unlikely (same generated bytes); keep searching.
            continue

        elapsed = time.perf_counter() - t0

        # Safety checks: this must be a true collision.
        assert previous != message
        assert truncated_sha256_bits(previous, bits) == truncated_sha256_bits(message, bits)

        return CollisionResult(
            bits=bits,
            attempts=attempt,
            digest_value=digest_value,
            message_a=previous,
            message_b=message,
            elapsed_seconds=elapsed,
        )

    raise RuntimeError(f"no collision found within max_attempts={max_attempts} for {bits}-bit hash")


def run_trials(bits: int, trials: int, max_attempts: int, base_seed: int = 20260407) -> tuple[np.ndarray, CollisionResult]:
    """Run repeated collision searches and return attempts + one sample collision."""
    attempts = np.zeros(trials, dtype=np.int64)
    sample: CollisionResult | None = None

    for i in range(trials):
        trial_seed = base_seed + bits * 10_007 + i * 97
        result = find_first_collision(bits=bits, seed=trial_seed, max_attempts=max_attempts)
        attempts[i] = result.attempts
        if sample is None:
            sample = result

    assert sample is not None
    return attempts, sample


def short_hex(data: bytes, max_chars: int = 24) -> str:
    """Return truncated hex string for compact terminal output."""
    text = data.hex()
    if len(text) <= max_chars:
        return text
    return f"{text[:max_chars]}..."


def main() -> None:
    bit_settings = (20, 24, 28)
    trials = 5
    max_attempts = 800_000

    print("=== Birthday Attack MVP (Truncated SHA-256 Collision Search) ===")
    print(f"bit settings: {bit_settings}")
    print(f"trials per setting: {trials}")
    print(f"max attempts per trial: {max_attempts}")

    for bits in bit_settings:
        attempts, sample = run_trials(bits=bits, trials=trials, max_attempts=max_attempts)

        theory = expected_attempts(bits)
        mean_attempts = float(np.mean(attempts))
        median_attempts = float(np.median(attempts))
        std_attempts = float(np.std(attempts, ddof=0))
        ratio = mean_attempts / theory

        print(f"\n--- n = {bits} bits ---")
        print(f"theoretical E[k]: {theory:.2f}")
        print(f"empirical mean : {mean_attempts:.2f}")
        print(f"empirical median: {median_attempts:.2f}")
        print(f"empirical std  : {std_attempts:.2f}")
        print(f"mean/theory    : {ratio:.3f}")

        print("sample collision:")
        print(f"  attempts : {sample.attempts}")
        print(f"  digest   : {digest_hex(sample.digest_value, bits)}")
        print(f"  m1 (hex) : {short_hex(sample.message_a)}")
        print(f"  m2 (hex) : {short_hex(sample.message_b)}")
        print(f"  elapsed  : {sample.elapsed_seconds:.4f}s")

    print("\nConclusion: collision cost grows near O(2^(n/2)), matching birthday-attack theory.")


if __name__ == "__main__":
    main()
